name: units_converter
description: Simple and light units conversion package for all your needs.
version: 3.0.4
homepage: https://github.com/ferraridamiano/units_converter
repository: https://github.com/ferraridamiano/units_converter
issue_tracker: https://github.com/ferraridamiano/units_converter/issues
funding:
 - https://www.paypal.com/paypalme/DemApps
topics:
 - unit-converter
 - converter
 - tool

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
 flutter:
  sdk: flutter

dev_dependencies:
  lints: ">=4.0.0 <7.0.0"
  test: ^1.25.5

flutter:
 assets:
  - assets/language/en.json
  - assets/language/vi.json